kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm
steps:
- name: publish
  image: plugins/docker
  settings:
    repo: aleda145/resume-app
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
